name: Test project
#activity types
on: 
  #pull_request:
    #types:
     # - opened
  workflow_dispatch: 
  push:
    branches:
      - main # main
      #- 'dev-*' # dev-new dev-this-is-new
      #- 'feat/**' # feat/new feat/new/buttom
    paths:
      - 'public/vite.svg'
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        #step that downloads a code from our git hub repo into the runner or the server that is maintained by github
        uses: actions/checkout@v4

      - name: installed node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: install dependansies
        run: npm ci
      
      - name: run test
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: installed node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: install dependancies
        run: npm ci

      - name: create build
        run: npm run build

      - name: deploy code
        run: echo "code deployed"          
